### PR TITLE
Fix Text node to escape its content

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by pakastin** [comment]
Thank you so much for your great work! Gave you maintainer access to make it easier to work in the future 😉

**Comment by jirutka** [comment]
You’re welcome! :cat:

Thank you for your confidence! Do you wanna still peer-review all the contributions or shall I commit directly to the master?

**Comment by pakastin** [comment]
I'm actually not currently using NO:DOM, so I trust you 😎👍

**Comment by pakastin** [comment]
Just let me know when you want to release a new version to npm..

**Pull request merged**
